Repository nanoframework/nanoFramework.M5Stack, pull requests merged in 2022-01, with the labels that each got.

#52 Fixing resource not found in M5Core2.InitializeScreen()
  nanoFramework.M5Core2/Resource.Designer.cs
Labels: Type: bug

#53 Fixing NuGets and M5Core2 project
  nanoFramework.M5Core.nuspec
  nanoFramework.M5Core2.nuspec
  nanoFramework.M5Core2/nanoFramework.M5Core2.nfproj
  nanoFramework.M5Core2/packages.config
  nanoFramework.M5StickC.nuspec
  nanoFramework.M5StickCPlus.nuspec
Labels: Area: Config-and-Build

#54 Fixing resources for M5Core screen init
  Tests/M5CoreTestApp/M5CoreTestApp.nfproj
  nanoFramework.M5Core/M5Core.cs
  nanoFramework.M5Core/ResourceCore.Designer.cs
  nanoFramework.M5Core/ResourceCore.resx
  nanoFramework.M5Core/nanoFramework.M5Core.nfproj
Labels: Type: bug

#55 Fix touch screen and wifi issue when both in use
  Tests/M5Core2TestApp/Program.cs
Labels: Type: bug

#64 Adjusting red port pin number for M5Core2 and M5Core
  nanoFramework.M5Core/M5Core.cs
  nanoFramework.M5Core2/M5Core2.cs
  nanoFramework.M5StackCore/M5CoreBase.cs
Labels: Type: bug

#69 Fixing I2C creation for MPU6886 on M5Core2
  Tests/M5Core2TestApp/Program.cs
  nanoFramework.M5StackCore/M5CoreBase.cs
Labels: Type: bug

#71 Added support to Atom Lite
  README.md
  Tests/M5AtomLiteTestApp/M5AtomLiteTestApp.nfproj
  Tests/M5AtomLiteTestApp/Program.cs
  Tests/M5AtomLiteTestApp/Properties/AssemblyInfo.cs
  Tests/M5AtomLiteTestApp/packages.config
  nanoFramework.M5AtomLite.nuspec
  nanoFramework.M5AtomLite/M5AtomLite.cs
  nanoFramework.M5AtomLite/Properties/AssemblyInfo.cs
  nanoFramework.M5AtomLite/RgbLed.cs
  nanoFramework.M5AtomLite/key.snk
  nanoFramework.M5AtomLite/nanoFramework.M5AtomLite.nfproj
  nanoFramework.M5AtomLite/packages.config
  nanoFramework.M5Stack.sln
Labels: Type: documentation, Type: enhancement

#74 Rename Atom Lite namespace and projects
  README.md
  Tests/AtomLiteTestApp/AtomLiteTestApp.nfproj
  Tests/AtomLiteTestApp/Program.cs
  Tests/AtomLiteTestApp/Properties/AssemblyInfo.cs
  Tests/AtomLiteTestApp/packages.config
  azure-pipelines.yml
  nanoFramework.AtomLite.nuspec
  nanoFramework.AtomLite/AtomLite.cs
  nanoFramework.AtomLite/Properties/AssemblyInfo.cs
  nanoFramework.AtomLite/RgbLed.cs
  nanoFramework.AtomLite/key.snk
  nanoFramework.AtomLite/nanoFramework.AtomLite.nfproj
  nanoFramework.AtomLite/nanoFramework.M5AtomLite.nfproj
  nanoFramework.AtomLite/packages.config
  nanoFramework.M5Stack.sln
Labels: Area: Config-and-Build
